app = "nsa"   # replace with your Fly app name
primary_region = "mia"  # or whatever region you chose

[build]

[env]
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true