app = "nsa"  # Your Fly app name

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  # If you use Python, Fly uses a standard Python builder automatically

[env]
  PORT = "8080"  # Flask keep-alive port

[experimental]
  auto_rollback = true

[deploy]
  release_command = ""

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[deploy]
  release_command = ""
  
[processes]
  web = "python bot.py"

# Optional: specify region (replace 'dfw' with your preferred supported region)
[region]
  primary = "dfw"